API_KEY = "AK9AI45EYVTP7UX8OZFA"
API_SECRET = "09P5l1sChHRCO2nUEEWakNUiy287NM3aMXr20is2"
TESTAPI_KEY = "PKRZV60OQJ2WQYGJK6WX"
TESTAPI_SECRET = "sg7lXmjVAGgfOCR6fACzCeiQQwtLtc4iKswqrW0F"
WEBBSTREAM = "wss://data.alpaca.markets/stream"
#Not real
APCA_API_BASE_URL = "https://paper-api.alpaca.markets"